### PR TITLE
create german config

### PR DESCRIPTION
**Pull request by avalanchas**
Proposed German translation

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Sorry about the delay, real life intruded.
Thank you

**Comment by avalanchas** [comment]
> Sorry about the delay, real life intruded.
> Thank you

Oh please, never apologize! There was never any haste, I just didn't know if did everything correctly
Let's hope this leads into some more modding knowledge for me, maybe I can contribute some real code at some point :)
See you and thanks for your work

**Comment by linuxgurugamer** [comment]
Just curious, did you do the translation manually, or was it automatic?

**Comment by avalanchas** [comment]
Manual, I am German after all

**Comment by avalanchas** [comment]
But I think we have a bug, it should be "de-de" at the top of the file, right? :(

**Comment by linuxgurugamer** [comment]
Yes, I fixed it
And I didn't know you were german :-)
Thank you

**Pull request merged**
